### ISSUE TITLE
Mount USB saves

### ISSUE THREAD

**Issue by Buzbee** [ChendoChap/Playstation-4-Save-Mounter#10]
Any way to mount and decrypt 5.05 signed saves on usb? I can no longer use built in backup utility after reformat unless I update and sign in to PSN once. I could then use ps4 save mounter to transfer them to system.

Also, can you list all the directories a save file might detect a corrupt save ( including temporary files). I have a game that detects a corrupt save and tries to delete it and create a new save but just halts so i cant play the game. I didn't make any changes to the save but I had the game running and mounted in ps4 save mounter and forgot to unmount. PS4 doesnt detect a save and I checked user/home and nothing is there.

Maybe you could add a prompt to unmount when someone tries to close out program before unmounting.

**Comment by ChendoChap** [comment]
it's possible to do that but not with this tool or at least not in its current state but I can definitely tell you that it's possible.

every directory using the correct format is listed and it uses the .db to get the saves in a directory, I do mention in the readme that using savemounter while a game is running can trigger crashes and corruption of saves. removing the 2 files linked to the corrupt save and removing its entry from the db should restore functionality of that game.

that's manageable but I currently don't have a lot of time to work on this, adding this feature is rather ez so if anyone feels like jumping in... I accept PRs just so you guys know.
(goddamnit markdown)

**Comment by Buzbee** [comment]
I found out I needed to delete the game folder in the mnt/sandbox/NPSX21006_000/usr/appmeta folder. Now game is able to create new save.

Maybe you could find some time this summer to add USB save support. I am in no hurry.
