### ISSUE TITLE
Can't connect to save mounter FTP

### ISSUE THREAD

**Issue by Pysis868** [ChendoChap/Playstation-4-Save-Mounter#14]
I have PS-Phwoar and use that FTP payload fine.

When I start a save mounter payload from it as well, I can connect, but after the mount step I cannot FTP to the console anymore.

I have also tried starting with a bin loader v1.0 and this has the same issue.

It does not help starting the generic ftp payload before and I can see when I no longer can successfully connect to the FTP server, even when the save mounter's 2nd/3rd notification appears telling me I can..

Following this: https://www.psxhax.com/threads/ps4-save-mounter-gamesave-tutorial-by-hejran7.6093/

**Comment by ChendoChap** [comment]
You either need a persistent ftp payload (one that survives outside of the browser process) or you want to load the ftp payload after ps4debug and keep the browser open.
