### ISSUE TITLE
Use foreign saves

### ISSUE THREAD

**Issue by Remus72** [ChendoChap/Playstation-4-Save-Mounter#15]
I'd like to use someone else's savegame. So what do I have to do for?

For example CUSA01446 (Borderlands: The Handsome Collection)

In my case, there is in  mnt//pfs a .sav file. Just to replace doesn't work. So I tried the param.sfo editor 1.2, but it doesn't show me an account ID. Do I have to delete the NPX... folders? What exactly has to be done?
Thx for your advice!
(I do own the physical copy of the game, I just don't wanna grind for items anymore..)

**Comment by ChendoChap** [comment]
hard to tell what your exact issue is;
generally speaking games themselves don't have any mechanisms to prevent users from using other saves. It happens at an lower level and is handled by shellcore, although they technically could do it but I don't own that game so I can't exactly check.


when you want to use someone else's save you need the pfs image and its sealedkey (both need to use a key revision that's present on 5.05 consoles; so you can't use newer saves for this)
or you want a pre-decrypted savedata directory

then you just use a donor save (this has to be big enough to hold the new data (see the fallout 4 issue) and replace the files (don't replace the sce files)
