### ISSUE TITLE
Please support to system 6.72

### ISSUE THREAD

**Issue by YuriSizuku** [ChendoChap/Playstation-4-Save-Mounter#17]
The jailbreak 6.72 is coming out. Is it possible to support this system.

**Comment by ghost** [comment]
@ChendoChap if you ever get the time, please update 👍

**Comment by Avrution** [comment]
Hmm, so this doesn't still work with 6.72?  I have been waiting to recover a save from my console and was pretty excited to finally be able to do so - just assumed this was still working.  Here's hoping for an update then.

**Comment by krugdenis** [comment]
https://github.com/GiantPluto/Playstation-4-Save-Mounter
He is trying to update it for 6.72 FW

**Comment by lollipop6969** [comment]
@ChendoChap please update to 6.72 so we can copy in 5.05 savegames. btw does ps4debug also have to be updated, or does it work with every firmware?

everything would be so much easier if someone would update offline account activator to 6.72.

**Comment by YuriSizuku** [comment]
> https://github.com/GiantPluto/Playstation-4-Save-Mounter
> He is trying to update it for 6.72 FW

Is this possible now for 6.72 ?

**Comment by krugdenis** [comment]
> > https://github.com/GiantPluto/Playstation-4-Save-Mounter
> > He is trying to update it for 6.72 FW
> 
> Is this possible now for 6.72 ?

Updated with 6.72 offsets.
Users and save files enumeration works but mount patch is still broken.

**Comment by krugdenis** [comment]
https://github.com/D-Pyro/Playstation-4-Save-Mounter/releases/tag/6.72

**Comment by Myoko** [comment]
nobody update jkpatch?

**Comment by YuriSizuku** [comment]
> https://github.com/D-Pyro/Playstation-4-Save-Mounter/releases/tag/6.72

I try to use this, but it mounts failed with error CE-36329-3

**Comment by krugdenis** [comment]
https://github.com/GiantPluto/Playstation-4-Save-Mounter/releases/tag/v1.6

**Comment by YuriSizuku** [comment]
> https://github.com/GiantPluto/Playstation-4-Save-Mounter/releases/tag/v1.6

Thank you！I tested and it works.
