### ISSUE TITLE
Regarding 9.00 compatibility

### ISSUE THREAD

**Issue by riazmoradian** [ChendoChap/Playstation-4-Save-Mounter#20]
Any idea whether 9.00 compatibility will be included any time soon?

**Comment by Pharaoh2k** [comment]
A modded version seems to be available here:
https://gbatemp.net/threads/playstation-4-save-mounter-1-9-with-9-00-fw-support.604873/

**Comment by ghost** [comment]
That version has the wrong offsets for some patches but it does not affect Save Mounter itself.

**Comment by Pharaoh2k** [comment]
Try CTN versions then.
https://github.com/ctn123/Binary-Releases/releases/tag/Save_Mounter_v1.9.3_beta?s=09

t8 supposed to be the best.

**Comment by riazmoradian** [comment]
> Try CTN versions then. https://github.com/ctn123/Binary-Releases/releases/tag/Save_Mounter_v1.9.3_beta?s=09
> 
> t8 supposed to be the best.

Tried this out, worked flawlessly for me.
