### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by Aurangzeb56** [ChendoChap/Playstation-4-Save-Mounter#7]
Hey there,
I can't seem to be able to get the PS4 Save Mounter to work with me. I load the payload, open ftp, connect the PS4 Save Mounter and it does get connected. After that when I press the setup button, the program freezes doesn't respond. Please could you help me with this. Thank you.

EDIT: When I try to force close the app and let windows restore the app, I get this error,

Unhandeled exception has occurred in your application. If you click continue, the application wil ignore this error and attempt to continue. If you click quit, the application will close immediately.

An established connection was aborted by the software in your host machine.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

EDIT 2: Fixed the issue. I think maybe the EXT HDD was connected to my PS4 was causing the app to crash? I don't know but it's fixed now and there isn't any USB inserted in my PS4.

**Comment by Amnesc007** [comment]
i hav the same prblm and  dont hav any ext hdd inserted in my ps4.......pls hlp

**Comment by DocMaster-design** [comment]
Lo mismo. No encuentro ninguna ayuda que pueda saber la causa
