### ISSUE TITLE
PS4 Save Mounter not finding directories

### ISSUE THREAD

**Issue by Aurangzeb56** [ChendoChap/Playstation-4-Save-Mounter#8]
Hello @ChendoChap. I'm having some trouble finding directories for Kingdom Hearts 3 Save File which I copied from my Non-Hacked PS4. I copied the save through ftp in the "user/home/userID/" and refreshed the PS4 Save Mounter to get games. It found the Game ID which is CUSA12031. I clicked it and then went down to click search for finding the directories, but it comes up with 0 results. I tried doing this with Kingdom Hearts HD I.5 + II.5 Remix Save Data but it does not find any directories for that game as well. Could you help me please?

Kingdom Hearts 3 Save contains 
01. kh3sv 
02. kh3sv.bin

Kingdom Hearts HD I.5 + II.5 Remix contains 
01. CUSA05786-KINGDOMHEARTSEN
02. CUSA05786-KINGDOMHEARTSEN.bin
03. CUSA05786-KINGDOMHEARTSMARE
04. CUSA05786-KINGDOMHEARTSMARE.bin

Please help me.

**Comment by ChendoChap** [comment]
1) you can only do that if those saves came from a console <= 5.05, you can however make saves for 5.05+ ps4s as long as you have the account/psnid of the target account.

2) new saves that you just add over ftp need to be added to the savedata database for them to show up
replacing an existing save also works

3) those files are named incorrectly, each save has 2 files (the img & the sealedkey)
this is the correct way to do it.
(FILE 1) xxxxxxx.bin
(FILE 2) sdimg_xxxxxxx

eg:
kh3sv.bin
sdimg_kh3sv

**Comment by Aurangzeb56** [comment]
> 1. you can only do that if those saves came from a console <= 5.05, you can however make saves for 5.05+ ps4s as long as you have the account/psnid of the target account.
> 2. new saves that you just add over ftp need to be added to the savedata database for them to show up
>    replacing an existing save also works
> 3. those files are named incorrectly, each save has 2 files (the img & the sealedkey)
>    this is the correct way to do it.
>    (FILE 1) xxxxxxx.bin
>    (FILE 2) sdimg_xxxxxxx
> 
> eg:
> kh3sv.bin
> sdimg_kh3sv

Well the save came from 6.20 firmware in my original PS4 which also has my PSN account in it. I copied the save from that PS4 into my USB through the official PS4 save data transfer. My Hacked PS4 didn't had PSN enabled in It so I had to ftp the saves to the "User/home/savedata/" location.

I'm sorry for such a noobish quesiton, but how do I add them to the savedata database?

So renaming the files name through ftp will work?

**Comment by ChendoChap** [comment]
you're not going to be able to do anything with the saves you get from the 6.20 console.
It uses a newer keyset, one which is not present on 5.05 consoles so the console won't be able to do anything with it even if you add it to the savedata db.

the only thing you can do is create/resign saves from your 5.05 console for your 6.20 one, you'd be able to use any save on the condition that it's mountable on 5.05 & that you know your playstation id or whatever it's called, only way to get that (that I know of) is to open a param.sfo that was created by that account, urgh this is complicated to explain...
to use save mounter you need to have
- to have a 5.05 console or a 5.05+ console but only if you also have a save exported to usb (with the retail thing from settings) but it needs to be one from 5.05 or below since you need a way to mount it to get the account id/psn id anyway as I said before it's not that easy to explain & I'm guessing that you don't have a save from before 5.50... so I probably shouldn't waste too much time explaining something that you'll probably never be able to use.

**Comment by Aurangzeb56** [comment]
> you're not going to be able to do anything with the saves you get from the 6.20 console.
> It uses a newer keyset, one which is not present on 5.05 consoles so the console won't be able to do anything with it even if you add it to the savedata db.
> 
> the only thing you can do is create/resign saves from your 5.05 console for your 6.20 one, you'd be able to use any save on the condition that it's mountable on 5.05 & that you know your playstation id or whatever it's called, only way to get that (that I know of) is to open a param.sfo that was created by that account, urgh this is complicated to explain...
> to use save mounter you need to have
> 
> * to have a 5.05 console or a 5.05+ console but only if you also have a save exported to usb (with the retail thing from settings) but it needs to be one from 5.05 or below since you need a way to mount it to get the account id/psn id anyway as I said before it's not that easy to explain & I'm guessing that you don't have a save from before 5.50... so I probably shouldn't waste too much time explaining something that you'll probably never be able to use.

Hahahaha, no worries. I get what you are saying. We need higher firmware keys from PS4 for enc/dec of 5.05 + FW Save Data. I knew that through PS3 Bruteforce. :P I just became curious as a modder at YouTube named Xeeynamo said that we could decrypt our KH3 save file through your method to save edit it and then we can re-encrypt it and copy over our save to the Non-Hacked PS4 and play them. That was all. Also I do have a save in my PS4 from before 5.05 from which I can get the param.sfo and my account ID. Well anyways, thanks for the help. :)

**Comment by ChendoChap** [comment]
yea np and since you have the id you can use any 5.05 save on your 6.20 ps4 you just need to change the param.sfo while it's mounted on the 5.05 one.

**Comment by Aurangzeb56** [comment]
> yea np and since you have the id you can use any 5.05 save on your 6.20 ps4 you just need to change the param.sfo while it's mounted on the 5.05 one.

Thanks for that tip. :)
